#!/bin/bash
# Game server entrypoint.
#   1. Syncs host config/ template into the writable config volume.
#   2. Generates config/dbconfig.txt from environment variables.
#   3. Waits for MariaDB to accept connections.
#   4. Execs DreamDaemon.
set -euo pipefail

MYSQL_HOST="${MYSQL_HOST:-mariadb}"
MYSQL_USER="${MYSQL_USER:-ss13}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:?MYSQL_PASSWORD must be set}"

# ── Generate dbconfig.txt ─────────────────────────────────────────────────────
# Overwritten every start so it always reflects the current env vars.
mkdir -p /tgstation/config
cat > /tgstation/config/dbconfig.txt <<EOF
## Auto-generated by Docker entrypoint — do not edit by hand.
SQL_ENABLED

ADDRESS ${MYSQL_HOST}

PORT 3306

FEEDBACK_DATABASE ss13

FEEDBACK_TABLEPREFIX SS13_

FEEDBACK_LOGIN ${MYSQL_USER}

FEEDBACK_PASSWORD ${MYSQL_PASSWORD}

ASYNC_QUERY_TIMEOUT 10

BLOCKING_QUERY_TIMEOUT 5

BSQL_THREAD_LIMIT 50
EOF

# ── Wait for MariaDB ──────────────────────────────────────────────────────────
echo "Waiting for MariaDB at ${MYSQL_HOST}..."
until mysqladmin ping \
        -h "${MYSQL_HOST}" \
        -u "${MYSQL_USER}" \
        -p"${MYSQL_PASSWORD}" \
        --silent 2>/dev/null; do
    echo "  MariaDB not ready — retrying in 2 s..."
    sleep 2
done
echo "MariaDB is up."

# ── Start DreamDaemon ─────────────────────────────────────────────────────────
exec DreamDaemon hippiestation.dmb \
    -port 1337 \
    -trusted \
    -close \
    -verbose \
    "$@"
